version: "3"

services:
  gateway:
    image: "${CODECOV_GATEWAY_IMAGE}"
    volumes:
      - ./config:/config
      #- ${CODECOV_SSL_CERT-/cert/codecov.crt}:/etc/codecov/ssl/certs/cert.crt:ro # uncomment if using ssl
    ports:
      - "${CODECOV_EXPOSED_GATEWAY:-127.0.0.1:8080}:8080"
      #- "${CODECOV_SSL_PORT-8443}:8443" # uncomment if using ssl
    environment:
      - CODECOV_GATEWAY_MINIO_ENABLED=true
      #- CODECOV_GATEWAY_SSL_ENABLED=true # uncomment if using ssl
    networks:
      - codecov
    depends_on:
      - api
      - frontend

  frontend:
    image: "${CODECOV_FRONTEND_IMAGE}"
    environment:
      - CODECOV_BASE_HOST=${CODECOV_PUBLIC_HOST}
      - CODECOV_API_HOST=${CODECOV_PUBLIC_HOST}
      - CODECOV_IA_HOST=${CODECOV_PUBLIC_HOST}
      - CODECOV_SCHEME=http
    volumes:
      - ./config:/config
    networks:
      - codecov

  api:
    image: "${CODECOV_API_IMAGE}"
    # build: # uncomment if on a mac
    #   dockerfile: ./m1-build-fix/Dockerfile
    #   context: .
    command: "/home/api run"
    volumes:
      - ./config:/config
    networks:
      - codecov
    depends_on:
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      timescale:
        condition: service_healthy

  worker:
    image: "${CODECOV_WORKER_IMAGE}"
    command: worker
    volumes:
      - ./config:/config
      - archive-volume:/archive
    networks:
      - codecov
    depends_on:
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      timescale:
        condition: service_healthy

  redis:
    image: redis:6-alpine
    volumes:
      - redis-volume:/data
    networks:
      - codecov
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres -d postgres"
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - codecov

  timescale:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - timescale-volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres -d postgres"
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - codecov

  minio:
    image: minio/minio:RELEASE.2020-04-15T00-39-01Z
    command: server /export
    environment:
      - MINIO_ACCESS_KEY=codecov-default-key
      - MINIO_SECRET_KEY=codecov-default-secret
    volumes:
      - archive-volume:/export
    networks:
      - codecov
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:9000/minio/health/live"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres-volume:
  timescale-volume:
  redis-volume:
  archive-volume:

networks:
  codecov:
    driver: bridge
